# Data Science homework 1

## Modules:

In [1]:
import numpy as np

## 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [32]:
vector = np.random.randint(1, 11, size=10)

In [33]:
print(vector)

[ 3 10  8  2  2  8  8  9  1  2]


## 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення

In [5]:
arr_zero = np.zeros((3, 3), dtype=int)

In [6]:
print(arr_zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [20]:
arr_rnd = np.random.randint(1, 11, size = (5, 5))

In [21]:
print(arr_rnd)

[[ 7  4  6  3  1]
 [ 6  1  5  3  5]
 [ 6  5  4  8  3]
 [10  9  4  3  2]
 [ 4  2  5  6  9]]


## 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [17]:
arr_rnd = np.random.random((4, 4))

In [18]:
print(arr_rnd)

[[0.80243541 0.5621568  0.58432254 0.86608203]
 [0.71655523 0.74997937 0.86214575 0.93977391]
 [0.76208361 0.65182184 0.63123007 0.64655406]
 [0.57288436 0.16451148 0.08199285 0.25725721]]


# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [26]:
arr_1 = np.random.randint(1, 11, size = 5)

In [27]:
arr_2 = np.random.randint(1, 11, size = 5)

In [28]:
# Додавання
print(arr_1 + arr_2)

[15 15  6  9  3]


In [29]:
# Віднімання
print(arr_1 - arr_2)

[ 1 -5 -4  5 -1]


In [30]:
# Множення
print(arr_1 * arr_2)

[56 50  5 14  2]


# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [21]:
vector_1 = np.random.randint(1, 100, size = 7)

In [22]:
vector_2 =np.random.randint(1, 100, size = 7)

In [23]:
# Перший вектор
print(vector_1)

[19 45 26 81 65 38 65]


In [24]:
# Другий вектор
print(vector_2)

[73  9 47 20 59 16 22]


In [25]:
# Скалярний добуток
print(np.dot(vector_1, vector_2))

10507


# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [16]:
arr_1 = np.random.randint(1, 11, size = (2, 2))

In [17]:
# Матриця 2х2
print(arr_1)

[[ 3  6]
 [10  3]]


In [18]:
arr_2 = np.random.randint(1, 11, size = (2, 3))

In [19]:
# Матриця 2х3
print(arr_2)

[[10 10 10]
 [ 2  7  8]]


In [20]:
# Результат множення двох матриць
print(np.dot(arr_1, arr_2))

[[ 42  72  78]
 [106 121 124]]


# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [8]:
arr = np.random.randint(1, 11, size = (3, 3))

In [10]:
arr_inv = np.linalg.inv(arr)

In [14]:
# Матриця розміром 3х3
print(arr)

[[ 3  8 10]
 [ 7  6  4]
 [ 8  7 10]]


In [15]:
# Обернена матриця
print(arr_inv)

[[-0.16161616  0.05050505  0.14141414]
 [ 0.19191919  0.25252525 -0.29292929]
 [-0.00505051 -0.21717172  0.19191919]]


# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [32]:
arr = np.random.random((4, 4))

In [38]:
# Матриця 4х4
print(arr)

[[0.25632241 0.04574274 0.98239219 0.55801591]
 [0.52930598 0.54664434 0.14974    0.17433484]
 [0.42282315 0.96976709 0.86500713 0.84986657]
 [0.27274738 0.56382244 0.71297755 0.98370933]]


In [39]:
arr_t = arr.T

In [40]:
# Транспонована матриця 4х4
print(arr_t)

[[0.25632241 0.52930598 0.42282315 0.27274738]
 [0.04574274 0.54664434 0.96976709 0.56382244]
 [0.98239219 0.14974    0.86500713 0.71297755]
 [0.55801591 0.17433484 0.84986657 0.98370933]]


# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [41]:
vector = np.random.randint(1, 11, size = 4)

In [42]:
arr = np.random.randint(1, 11, size = (3, 4))

In [43]:
print(vector)

[4 8 3 4]


In [44]:
print(arr)

[[ 6  1  1  7]
 [10  8  5  9]
 [ 8  5  1  7]]


In [46]:
print(np.dot(arr, vector))

[ 63 155 103]


# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [47]:
vector = np.random.random(3)

In [48]:
print(vector)

[0.28858836 0.33858412 0.85857552]


In [49]:
arr = np.random.random((2, 3))

In [50]:
print(arr)

[[0.58329289 0.07202132 0.8638529 ]
 [0.28768369 0.94881828 0.09936643]]


In [51]:
print(np.dot(arr, vector))

[0.93439976 0.48959056]


# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [60]:
arr_1 = np.random.randint(1, 11, size=(2, 2))

In [61]:
arr_2 = np.random.randint(1, 11, size=(2, 2))

In [62]:
print(arr_1*arr_2)

[[48 12]
 [30 90]]


# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [3]:
arr_1 = np.random.randint(1, 11, size=(2, 2))
print(arr_1)

[[5 5]
 [9 3]]


In [4]:
arr_2 = np.random.randint(1, 11, size=(2, 2))
print(arr_2)

[[ 5  7]
 [ 3 10]]


In [11]:
# Добуток
print(np.dot(arr_1, arr_2))

[[40 85]
 [54 93]]


# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [9]:
arr = np.random.randint(1, 101, size=(5, 5))
print(arr)

[[ 76  98  31  78   5]
 [ 55  57  38   9  88]
 [ 73  78 100  67   9]
 [ 40  13  23  92  47]
 [ 97  19   3  89   5]]


In [13]:
# Сума елементів матриці arr
print(np.sum(arr))

1290


# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [14]:
arr_1 = np.random.randint(1, 11, size=(4, 4))
print(arr_1)

[[ 4 10  6  6]
 [ 1  4  6  5]
 [ 7  3  3  2]
 [ 6  7  4  2]]


In [15]:
arr_2 = np.random.randint(1, 11, size = (4, 4))
print(arr_2)

[[10  5  5  6]
 [ 3  6  6  4]
 [ 9  7  4  7]
 [10  8  1  3]]


In [17]:
# Різниця двох матриць
print(arr_1 - arr_2)

[[-6  5  1  0]
 [-2 -2  0  1]
 [-2 -4 -1 -5]
 [-4 -1  3 -1]]


# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [18]:
vector = np.random.randint(1, 51, size = 4)
print(vector)

[19 10 36  7]
